### ISSUE TITLE
Nice job!

### ISSUE THREAD

**Issue by msarahan** [tartansandal/bash-completion-recipe#1]
You put a lot of good thought and effort into this.  Thank you.  A good next step here is probably to create a conda-forge recipe.  To do that, you just clone https://github.com/conda-forge/staged-recipes and copy your recipe here into a new subfolder in the "recipes" folder.  Submit a PR to conda-forge/staged-recipes from your branch, and the conda-forge automation will build things for you.  When your PR is merged, it will be available on the conda-forge channel.

Anaconda's "defaults" treats conda-forge as an upstream.  It's not a hard requirement that things be added to conda-forge before defaults, but it does make life easier, because their CI infrastructure and linting are nicer than ours.

If you go ahead with conda-forge, feel free to ping me if you have trouble.

**Comment by tartansandal** [comment]
Thanks Mike. I've made the following PRs:

* `bash-completion`: https://github.com/conda-forge/staged-recipes/pull/10157
* `conda-bash-completion`: https://github.com/conda-forge/staged-recipes/pull/10158.

The latter is failing because it depends on the `bash-completion` package. 
Also getting failures for the MacOS and Windows builds -- not sure what to do about that at the moment.

**Comment by tartansandal** [comment]
This has now all been moved to conda-forge, and all future recipe development will happen there, so I'm going to archive this initial development repository.
